server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true

spring:
  datasource:
    url: jdbc:postgresql://dpg-cnd1gteg1b2c739khu4g-a.oregon-postgres.render.com:5432/final_project_qyq5
    username: final_project_qyq5_user
    password: A95rEq0AjOa9SHSDgG11zOaXiDdfYLQN
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect



