server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/final_project
    username: postgres
    password: xayala2003
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect



